### ISSUE TITLE
Depending on Moose?..

### ISSUE THREAD

**Issue by kberov** [gryphonshafer/exact#1]
Can somehow depending on Moose via TryCatch be avoided?
Maybe TryCatch can be replaced with something else like Try::Tiny or Try::Catch?

**Comment by gryphonshafer** [comment]
I can look into it. I'm not a fan of the Try::Tiny and Try::Catch caveats. I'd love to find a functional equivalent of TryCatch that doesn't depend on Moose.

**Comment by gryphonshafer** [comment]
After some thought and digging, I'm going to replace TryCatch with Try::Tiny. It's already in the dependency tree, and I can live with its caveats to remove a huge dependency burden. I've pushed 802eabd, which resolves this. I'm waiting on regression tests to come back passing, then I'll release to CPAN.

**Comment by kberov** [comment]
O! This is great. I am sure this will boost the usage of this module.
