### ISSUE TITLE
parent class import methods called with unexpected arguments

### ISSUE THREAD

**Issue by haarg** [gryphonshafer/exact#4]
When using code like `use exact qw(MyParent);`, exact will call `MyParent->import($caller)` if `MyParent` has an import method. This isn't how most import methods are expecting to be called. Most modules using inheritance aren't expecting to be imported from at all. Additionally, future versions of perl are intending to always provide a `UNIVERSAL::import` method, which will throw errors if passed arguments.

For the `exact::*` modules, this is required, so I'm not sure what the best solution for this. Possibly only calling import for `exact::` extensions.

**Comment by gryphonshafer** [comment]
Thanks for the report. I've been away on vacation, but I'll try to address this issue this week.
