### ISSUE TITLE
BBC: Bleadperl 5.41.3 breaks exact-1.25 (due smartmatch removal)

### ISSUE THREAD

**Issue by andk** [gryphonshafer/exact#5]
Fail report: http://www.cpantesters.org/cpan/report/3f294dd0-6ac3-11ef-85f3-11b004d2b116

**Comment by andk** [comment]
Apparently fixed in 1.26.

**Comment by gryphonshafer** [comment]
Oops. Forgot to close the issue. Yes, fixed via df8dd41. Basically, it was an overly aggressive test.

**Comment by gryphonshafer** [comment]
Oops. I forgot to note this in the issue an close it yesterday. The issue is "fixed" via 1cb8c96. The issue was an overly aggressive simple test.
